from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

# Función otras Vistas
from ui_cliente import *
from ui_productos import *
from ui_facturas import *

# Vista
class Ui_MainWindow(QFacturas, QProductos, QCliente, object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QSize(1000, 500))
        MainWindow.setStyleSheet(u"background-color: rgb(45, 45, 45);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Content = QFrame(self.centralwidget)
        self.Content.setObjectName(u"Content")
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_left_menu = QFrame(self.Content)
        self.frame_left_menu.setObjectName(u"frame_left_menu")
        self.frame_left_menu.setMinimumSize(QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet(u"background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_top_menus = QFrame(self.frame_left_menu)
        self.frame_top_menus.setObjectName(u"frame_top_menus")
        self.frame_top_menus.setFrameShape(QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_clientes = QPushButton(self.frame_top_menus)
        self.btn_clientes.setObjectName(u"btn_clientes")
        self.btn_clientes.setMinimumSize(QSize(0, 40))
        self.btn_clientes.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_clientes)

        self.btn_productos = QPushButton(self.frame_top_menus)
        self.btn_productos.setObjectName(u"btn_productos")
        self.btn_productos.setMinimumSize(QSize(0, 40))
        self.btn_productos.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_productos)

        self.btn_facturas = QPushButton(self.frame_top_menus)
        self.btn_facturas.setObjectName(u"btn_facturas")
        self.btn_facturas.setMinimumSize(QSize(0, 40))
        self.btn_facturas.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_facturas)


        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, Qt.AlignTop)


        self.horizontalLayout_2.addWidget(self.frame_left_menu)

        self.frame_pages = QFrame(self.Content)
        self.frame_pages.setObjectName(u"frame_pages")
        self.frame_pages.setFrameShape(QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.stackedWidget = QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.page_1.setEnabled(True)
        self.verticalLayout_7 = QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.f_clientes = QFrame(self.page_1)
        self.f_clientes.setObjectName(u"f_clientes")
        self.f_clientes.setFrameShape(QFrame.StyledPanel)
        self.f_clientes.setFrameShadow(QFrame.Raised)
        self.table_clientes = QTableWidget(self.f_clientes)
        if (self.table_clientes.columnCount() < 3):
            self.table_clientes.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.table_clientes.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.table_clientes.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.table_clientes.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.table_clientes.setObjectName(u"table_clientes")
        self.table_clientes.setGeometry(QRect(480, 250, 381, 192))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_clientes.sizePolicy().hasHeightForWidth())
        self.table_clientes.setSizePolicy(sizePolicy)
        self.table_clientes.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.table_clientes.setFrameShape(QFrame.NoFrame)
        self.table_clientes.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.gb_aClientes = QGroupBox(self.f_clientes)
        self.gb_aClientes.setObjectName(u"gb_aClientes")
        self.gb_aClientes.setGeometry(QRect(10, 0, 421, 431))
        font = QFont()
        font.setFamily(u"Segoe UI")
        self.gb_aClientes.setFont(font)
        self.gb_aClientes.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.f_cedula = QLineEdit(self.gb_aClientes)
        self.f_cedula.setObjectName(u"f_cedula")
        self.f_cedula.setGeometry(QRect(90, 90, 211, 31))
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(18)
        self.f_cedula.setFont(font1)
        self.l_ced = QLabel(self.gb_aClientes)
        self.l_ced.setObjectName(u"l_ced")
        self.l_ced.setGeometry(QRect(130, 40, 131, 41))
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(22)
        self.l_ced.setFont(font2)
        self.line = QFrame(self.gb_aClientes)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 130, 401, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.l_nom = QLabel(self.gb_aClientes)
        self.l_nom.setObjectName(u"l_nom")
        self.l_nom.setGeometry(QRect(130, 140, 151, 41))
        self.l_nom.setFont(font2)
        self.f_nombre = QLineEdit(self.gb_aClientes)
        self.f_nombre.setObjectName(u"f_nombre")
        self.f_nombre.setGeometry(QRect(90, 190, 211, 31))
        self.f_nombre.setFont(font1)
        self.line_2 = QFrame(self.gb_aClientes)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 240, 401, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.l_prod = QLabel(self.gb_aClientes)
        self.l_prod.setObjectName(u"l_prod")
        self.l_prod.setGeometry(QRect(130, 250, 151, 41))
        self.l_prod.setFont(font2)
        self.f_apellido = QLineEdit(self.gb_aClientes)
        self.f_apellido.setObjectName(u"f_apellido")
        self.f_apellido.setGeometry(QRect(90, 300, 211, 31))
        self.f_apellido.setFont(font1)
        self.btn_actualizar = QPushButton(self.gb_aClientes)
        self.btn_actualizar.setObjectName(u"btn_actualizar")
        self.btn_actualizar.setGeometry(QRect(70, 370, 121, 41))
        self.btn_actualizar.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.btn_agregar = QPushButton(self.gb_aClientes)
        self.btn_agregar.setObjectName(u"btn_agregar")
        self.btn_agregar.setGeometry(QRect(220, 370, 121, 41))
        self.btn_agregar.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.gb_eClientes = QGroupBox(self.f_clientes)
        self.gb_eClientes.setObjectName(u"gb_eClientes")
        self.gb_eClientes.setGeometry(QRect(450, 0, 421, 211))
        self.gb_eClientes.setFont(font)
        self.gb_eClientes.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.btn_eliminar = QPushButton(self.gb_eClientes)
        self.btn_eliminar.setObjectName(u"btn_eliminar")
        self.btn_eliminar.setGeometry(QRect(150, 130, 121, 41))
        self.btn_eliminar.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.l_bCedula = QLabel(self.gb_eClientes)
        self.l_bCedula.setObjectName(u"l_bCedula")
        self.l_bCedula.setGeometry(QRect(140, 20, 131, 41))
        self.l_bCedula.setFont(font2)
        self.f_bCedula = QLineEdit(self.gb_eClientes)
        self.f_bCedula.setObjectName(u"f_bCedula")
        self.f_bCedula.setGeometry(QRect(100, 70, 211, 31))
        self.f_bCedula.setFont(font1)

        self.verticalLayout_7.addWidget(self.f_clientes)

        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.verticalLayout_6 = QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.f_productos = QFrame(self.page_2)
        self.f_productos.setObjectName(u"f_productos")
        self.f_productos.setFrameShape(QFrame.StyledPanel)
        self.f_productos.setFrameShadow(QFrame.Raised)
        self.group_addP = QGroupBox(self.f_productos)
        self.group_addP.setObjectName(u"group_addP")
        self.group_addP.setGeometry(QRect(10, 10, 411, 441))
        self.group_addP.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_antibiotico = QPushButton(self.group_addP)
        self.btn_antibiotico.setObjectName(u"btn_antibiotico")
        self.btn_antibiotico.setGeometry(QRect(20, 20, 68, 40))
        self.btn_antibiotico.setMinimumSize(QSize(0, 40))
        self.btn_antibiotico.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_productoControl = QPushButton(self.group_addP)
        self.btn_productoControl.setObjectName(u"btn_productoControl")
        self.btn_productoControl.setGeometry(QRect(100, 20, 61, 40))
        self.btn_productoControl.setMinimumSize(QSize(0, 40))
        self.btn_productoControl.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")
        self.stacked_productos = QStackedWidget(self.group_addP)
        self.stacked_productos.setObjectName(u"stacked_productos")
        self.stacked_productos.setGeometry(QRect(20, 70, 371, 351))
        self.page_a = QWidget()
        self.page_a.setObjectName(u"page_a")
        self.form_antNombre = QLineEdit(self.page_a)
        self.form_antNombre.setObjectName(u"form_antNombre")
        self.form_antNombre.setGeometry(QRect(90, 30, 171, 21))
        font3 = QFont()
        font3.setFamily(u"Segoe UI")
        font3.setPointSize(12)
        self.form_antNombre.setFont(font3)
        self.label_antNom = QLabel(self.page_a)
        self.label_antNom.setObjectName(u"label_antNom")
        self.label_antNom.setGeometry(QRect(90, 10, 201, 21))
        font4 = QFont()
        font4.setFamily(u"Segoe UI")
        font4.setPointSize(14)
        self.label_antNom.setFont(font4)
        self.label_dosis = QLabel(self.page_a)
        self.label_dosis.setObjectName(u"label_dosis")
        self.label_dosis.setGeometry(QRect(90, 70, 201, 21))
        self.label_dosis.setFont(font4)
        self.form_dosis = QLineEdit(self.page_a)
        self.form_dosis.setObjectName(u"form_dosis")
        self.form_dosis.setGeometry(QRect(90, 90, 171, 21))
        self.form_dosis.setFont(font3)
        self.label_animal = QLabel(self.page_a)
        self.label_animal.setObjectName(u"label_animal")
        self.label_animal.setGeometry(QRect(90, 130, 201, 21))
        self.label_animal.setFont(font4)
        self.form_animal = QComboBox(self.page_a)
        self.form_animal.addItem("")
        self.form_animal.addItem("")
        self.form_animal.addItem("")
        self.form_animal.addItem("")
        self.form_animal.setObjectName(u"form_animal")
        self.form_animal.setGeometry(QRect(90, 150, 171, 22))
        self.form_animal.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_precio = QLabel(self.page_a)
        self.label_precio.setObjectName(u"label_precio")
        self.label_precio.setGeometry(QRect(90, 190, 201, 21))
        self.label_precio.setFont(font4)
        self.form_precio = QLineEdit(self.page_a)
        self.form_precio.setObjectName(u"form_precio")
        self.form_precio.setGeometry(QRect(90, 220, 171, 21))
        self.form_precio.setFont(font3)
        self.btn_agregarAnt = QPushButton(self.page_a)
        self.btn_agregarAnt.setObjectName(u"btn_agregarAnt")
        self.btn_agregarAnt.setGeometry(QRect(110, 270, 121, 41))
        self.btn_agregarAnt.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.stacked_productos.addWidget(self.page_a)
        self.page_pC = QWidget()
        self.page_pC.setObjectName(u"page_pC")
        self.form_ICA = QLineEdit(self.page_pC)
        self.form_ICA.setObjectName(u"form_ICA")
        self.form_ICA.setGeometry(QRect(90, 40, 171, 21))
        self.form_ICA.setFont(font3)
        self.label_ICA = QLabel(self.page_pC)
        self.label_ICA.setObjectName(u"label_ICA")
        self.label_ICA.setGeometry(QRect(90, 20, 201, 21))
        self.label_ICA.setFont(font4)
        self.label_nombrePro = QLabel(self.page_pC)
        self.label_nombrePro.setObjectName(u"label_nombrePro")
        self.label_nombrePro.setGeometry(QRect(90, 80, 201, 21))
        self.label_nombrePro.setFont(font4)
        self.form_nombrePro = QLineEdit(self.page_pC)
        self.form_nombrePro.setObjectName(u"form_nombrePro")
        self.form_nombrePro.setGeometry(QRect(90, 100, 171, 21))
        self.form_nombrePro.setFont(font3)
        self.label_frec = QLabel(self.page_pC)
        self.label_frec.setObjectName(u"label_frec")
        self.label_frec.setGeometry(QRect(90, 140, 211, 21))
        self.label_frec.setFont(font4)
        self.form_frec = QLineEdit(self.page_pC)
        self.form_frec.setObjectName(u"form_frec")
        self.form_frec.setGeometry(QRect(90, 160, 171, 21))
        self.form_frec.setFont(font3)
        self.label_precioP = QLabel(self.page_pC)
        self.label_precioP.setObjectName(u"label_precioP")
        self.label_precioP.setGeometry(QRect(90, 210, 211, 21))
        self.label_precioP.setFont(font4)
        self.form_precioP = QLineEdit(self.page_pC)
        self.form_precioP.setObjectName(u"form_precioP")
        self.form_precioP.setGeometry(QRect(90, 230, 171, 21))
        self.form_precioP.setFont(font3)
        self.btn_agregarP = QPushButton(self.page_pC)
        self.btn_agregarP.setObjectName(u"btn_agregarP")
        self.btn_agregarP.setGeometry(QRect(120, 280, 121, 41))
        self.btn_agregarP.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.stacked_productos.addWidget(self.page_pC)
        self.page_pFert = QWidget()
        self.page_pFert.setObjectName(u"page_pFert")
        self.form_nombrePro_2 = QLineEdit(self.page_pFert)
        self.form_nombrePro_2.setObjectName(u"form_nombrePro_2")
        self.form_nombrePro_2.setGeometry(QRect(90, 80, 171, 21))
        self.form_nombrePro_2.setFont(font3)
        self.label_frec_2 = QLabel(self.page_pFert)
        self.label_frec_2.setObjectName(u"label_frec_2")
        self.label_frec_2.setGeometry(QRect(90, 120, 211, 21))
        self.label_frec_2.setFont(font4)
        self.form_frec_2 = QLineEdit(self.page_pFert)
        self.form_frec_2.setObjectName(u"form_frec_2")
        self.form_frec_2.setGeometry(QRect(90, 140, 171, 21))
        self.form_frec_2.setFont(font3)
        self.form_precioP_2 = QLineEdit(self.page_pFert)
        self.form_precioP_2.setObjectName(u"form_precioP_2")
        self.form_precioP_2.setGeometry(QRect(90, 200, 171, 21))
        self.form_precioP_2.setFont(font3)
        self.form_ICA_2 = QLineEdit(self.page_pFert)
        self.form_ICA_2.setObjectName(u"form_ICA_2")
        self.form_ICA_2.setGeometry(QRect(90, 20, 171, 21))
        self.form_ICA_2.setFont(font3)
        self.label_ICA_2 = QLabel(self.page_pFert)
        self.label_ICA_2.setObjectName(u"label_ICA_2")
        self.label_ICA_2.setGeometry(QRect(90, 0, 201, 21))
        self.label_ICA_2.setFont(font4)
        self.label_precioP_2 = QLabel(self.page_pFert)
        self.label_precioP_2.setObjectName(u"label_precioP_2")
        self.label_precioP_2.setGeometry(QRect(90, 180, 211, 21))
        self.label_precioP_2.setFont(font4)
        self.btn_agregarP_2 = QPushButton(self.page_pFert)
        self.btn_agregarP_2.setObjectName(u"btn_agregarP_2")
        self.btn_agregarP_2.setGeometry(QRect(120, 300, 121, 41))
        self.btn_agregarP_2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.label_nombrePro_2 = QLabel(self.page_pFert)
        self.label_nombrePro_2.setObjectName(u"label_nombrePro_2")
        self.label_nombrePro_2.setGeometry(QRect(90, 60, 201, 21))
        self.label_nombrePro_2.setFont(font4)
        self.form_carencia = QLineEdit(self.page_pFert)
        self.form_carencia.setObjectName(u"form_carencia")
        self.form_carencia.setGeometry(QRect(90, 260, 171, 21))
        self.form_carencia.setFont(font3)
        self.label_carencia = QLabel(self.page_pFert)
        self.label_carencia.setObjectName(u"label_carencia")
        self.label_carencia.setGeometry(QRect(90, 240, 211, 21))
        self.label_carencia.setFont(font4)
        self.stacked_productos.addWidget(self.page_pFert)
        self.page_pPlaga = QWidget()
        self.page_pPlaga.setObjectName(u"page_pPlaga")
        self.form_precioP_3 = QLineEdit(self.page_pPlaga)
        self.form_precioP_3.setObjectName(u"form_precioP_3")
        self.form_precioP_3.setGeometry(QRect(100, 210, 171, 21))
        self.form_precioP_3.setFont(font3)
        self.label_frec_3 = QLabel(self.page_pPlaga)
        self.label_frec_3.setObjectName(u"label_frec_3")
        self.label_frec_3.setGeometry(QRect(100, 130, 211, 21))
        self.label_frec_3.setFont(font4)
        self.btn_agregarP_3 = QPushButton(self.page_pPlaga)
        self.btn_agregarP_3.setObjectName(u"btn_agregarP_3")
        self.btn_agregarP_3.setGeometry(QRect(130, 310, 121, 41))
        self.btn_agregarP_3.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.label_precioP_3 = QLabel(self.page_pPlaga)
        self.label_precioP_3.setObjectName(u"label_precioP_3")
        self.label_precioP_3.setGeometry(QRect(100, 190, 211, 21))
        self.label_precioP_3.setFont(font4)
        self.label_carencia_2 = QLabel(self.page_pPlaga)
        self.label_carencia_2.setObjectName(u"label_carencia_2")
        self.label_carencia_2.setGeometry(QRect(100, 250, 231, 21))
        self.label_carencia_2.setFont(font4)
        self.label_nombrePro_3 = QLabel(self.page_pPlaga)
        self.label_nombrePro_3.setObjectName(u"label_nombrePro_3")
        self.label_nombrePro_3.setGeometry(QRect(100, 70, 201, 21))
        self.label_nombrePro_3.setFont(font4)
        self.label_ICA_3 = QLabel(self.page_pPlaga)
        self.label_ICA_3.setObjectName(u"label_ICA_3")
        self.label_ICA_3.setGeometry(QRect(100, 10, 201, 21))
        self.label_ICA_3.setFont(font4)
        self.form_nombrePro_3 = QLineEdit(self.page_pPlaga)
        self.form_nombrePro_3.setObjectName(u"form_nombrePro_3")
        self.form_nombrePro_3.setGeometry(QRect(100, 90, 171, 21))
        self.form_nombrePro_3.setFont(font3)
        self.form_ICA_3 = QLineEdit(self.page_pPlaga)
        self.form_ICA_3.setObjectName(u"form_ICA_3")
        self.form_ICA_3.setGeometry(QRect(100, 30, 171, 21))
        self.form_ICA_3.setFont(font3)
        self.form_ultimaFechaAp = QLineEdit(self.page_pPlaga)
        self.form_ultimaFechaAp.setObjectName(u"form_ultimaFechaAp")
        self.form_ultimaFechaAp.setGeometry(QRect(100, 270, 171, 21))
        self.form_ultimaFechaAp.setFont(font3)
        self.form_frec_3 = QLineEdit(self.page_pPlaga)
        self.form_frec_3.setObjectName(u"form_frec_3")
        self.form_frec_3.setGeometry(QRect(100, 150, 171, 21))
        self.form_frec_3.setFont(font3)
        self.stacked_productos.addWidget(self.page_pPlaga)
        self.btn_productoControl_2 = QPushButton(self.group_addP)
        self.btn_productoControl_2.setObjectName(u"btn_productoControl_2")
        self.btn_productoControl_2.setGeometry(QRect(180, 20, 81, 40))
        self.btn_productoControl_2.setMinimumSize(QSize(0, 40))
        self.btn_productoControl_2.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_productoControl_3 = QPushButton(self.group_addP)
        self.btn_productoControl_3.setObjectName(u"btn_productoControl_3")
        self.btn_productoControl_3.setGeometry(QRect(280, 20, 81, 40))
        self.btn_productoControl_3.setMinimumSize(QSize(0, 40))
        self.btn_productoControl_3.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")
        self.group_delP = QGroupBox(self.f_productos)
        self.group_delP.setObjectName(u"group_delP")
        self.group_delP.setGeometry(QRect(450, 10, 431, 71))
        self.group_delP.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_eProd = QLabel(self.group_delP)
        self.label_eProd.setObjectName(u"label_eProd")
        self.label_eProd.setGeometry(QRect(10, 20, 181, 21))
        self.label_eProd.setFont(font4)
        self.form_eProd = QLineEdit(self.group_delP)
        self.form_eProd.setObjectName(u"form_eProd")
        self.form_eProd.setGeometry(QRect(200, 20, 171, 21))
        self.form_eProd.setFont(font3)
        self.btn_eProd = QPushButton(self.group_delP)
        self.btn_eProd.setObjectName(u"btn_eProd")
        self.btn_eProd.setGeometry(QRect(160, 50, 81, 16))
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setPointSize(8)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setWeight(50)
        self.btn_eProd.setFont(font5)
        self.btn_eProd.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"Segoe UI\";\n"
"border-color: rgb(91, 90, 100);")
        self.table_ProductosC = QTableWidget(self.f_productos)
        if (self.table_ProductosC.columnCount() < 4):
            self.table_ProductosC.setColumnCount(4)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.table_ProductosC.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.table_ProductosC.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.table_ProductosC.setHorizontalHeaderItem(2, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.table_ProductosC.setHorizontalHeaderItem(3, __qtablewidgetitem6)
        self.table_ProductosC.setObjectName(u"table_ProductosC")
        self.table_ProductosC.setGeometry(QRect(450, 100, 431, 151))
        self.table_ProductosC.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.table_ProductosC.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_Antibioticos = QTableWidget(self.f_productos)
        if (self.table_Antibioticos.columnCount() < 4):
            self.table_Antibioticos.setColumnCount(4)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.table_Antibioticos.setHorizontalHeaderItem(0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.table_Antibioticos.setHorizontalHeaderItem(1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.table_Antibioticos.setHorizontalHeaderItem(2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.table_Antibioticos.setHorizontalHeaderItem(3, __qtablewidgetitem10)
        self.table_Antibioticos.setObjectName(u"table_Antibioticos")
        self.table_Antibioticos.setGeometry(QRect(450, 280, 431, 161))
        self.table_Antibioticos.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.table_Antibioticos.setEditTriggers(QAbstractItemView.NoEditTriggers)

        self.verticalLayout_6.addWidget(self.f_productos)

        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.verticalLayout_8 = QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.f_facturas = QFrame(self.page_3)
        self.f_facturas.setObjectName(u"f_facturas")
        self.f_facturas.setFrameShape(QFrame.StyledPanel)
        self.f_facturas.setFrameShadow(QFrame.Raised)
        self.stacked_facturas = QStackedWidget(self.f_facturas)
        self.stacked_facturas.setObjectName(u"stacked_facturas")
        self.stacked_facturas.setGeometry(QRect(10, 50, 881, 401))
        self.p_clienteF = QWidget()
        self.p_clienteF.setObjectName(u"p_clienteF")
        self.stacked_facturas.addWidget(self.p_clienteF)
        self.p_crearF = QWidget()
        self.p_crearF.setObjectName(u"p_crearF")
        self.l_Ftotal = QLabel(self.p_crearF)
        self.l_Ftotal.setObjectName(u"l_Ftotal")
        self.l_Ftotal.setGeometry(QRect(740, 370, 91, 20))
        font6 = QFont()
        font6.setFamily(u"Open Sans Semibold")
        font6.setPointSize(11)
        font6.setBold(True)
        font6.setUnderline(True)
        font6.setWeight(75)
        self.l_Ftotal.setFont(font6)
        self.l_Ftotal.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.table_Fprods = QTableWidget(self.p_crearF)
        if (self.table_Fprods.columnCount() < 3):
            self.table_Fprods.setColumnCount(3)
        font7 = QFont()
        font7.setPointSize(11)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setFont(font7);
        self.table_Fprods.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        __qtablewidgetitem12.setFont(font7);
        self.table_Fprods.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setFont(font7);
        self.table_Fprods.setHorizontalHeaderItem(2, __qtablewidgetitem13)
        self.table_Fprods.setObjectName(u"table_Fprods")
        self.table_Fprods.setGeometry(QRect(350, 180, 501, 181))
        sizePolicy.setHeightForWidth(self.table_Fprods.sizePolicy().hasHeightForWidth())
        self.table_Fprods.setSizePolicy(sizePolicy)
        self.table_Fprods.setSizeIncrement(QSize(0, 0))
        self.table_Fprods.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.table_Fprods.setAutoFillBackground(False)
        self.table_Fprods.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.table_Fprods.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_Fprods.horizontalHeader().setCascadingSectionResizes(False)
        self.table_Fprods.horizontalHeader().setDefaultSectionSize(161)
        self.table_Ftotal = QTableWidget(self.p_crearF)
        if (self.table_Ftotal.rowCount() < 1):
            self.table_Ftotal.setRowCount(1)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.table_Ftotal.setVerticalHeaderItem(0, __qtablewidgetitem14)
        self.table_Ftotal.setObjectName(u"table_Ftotal")
        self.table_Ftotal.setGeometry(QRect(680, 360, 171, 31))
        sizePolicy.setHeightForWidth(self.table_Ftotal.sizePolicy().hasHeightForWidth())
        self.table_Ftotal.setSizePolicy(sizePolicy)
        self.table_Ftotal.setSizeIncrement(QSize(0, 0))
        self.table_Ftotal.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.table_Ftotal.setAutoFillBackground(False)
        self.table_Ftotal.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.table_Ftotal.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_Ftotal.horizontalHeader().setCascadingSectionResizes(False)
        self.table_Ftotal.horizontalHeader().setDefaultSectionSize(161)
        self.group_cData = QGroupBox(self.p_crearF)
        self.group_cData.setObjectName(u"group_cData")
        self.group_cData.setGeometry(QRect(20, 10, 261, 351))
        self.l_Fced = QLabel(self.group_cData)
        self.l_Fced.setObjectName(u"l_Fced")
        self.l_Fced.setGeometry(QRect(20, 20, 121, 20))
        font8 = QFont()
        font8.setFamily(u"Segoe UI")
        font8.setPointSize(16)
        self.l_Fced.setFont(font8)
        self.btn_Fcreate = QPushButton(self.group_cData)
        self.btn_Fcreate.setObjectName(u"btn_Fcreate")
        self.btn_Fcreate.setGeometry(QRect(60, 190, 151, 61))
        self.btn_Fcreate.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"border-color: rgb(255, 30, 30);")
        self.form_Fced = QLineEdit(self.group_cData)
        self.form_Fced.setObjectName(u"form_Fced")
        self.form_Fced.setGeometry(QRect(20, 50, 191, 21))
        self.form_Fdat = QDateEdit(self.group_cData)
        self.form_Fdat.setObjectName(u"form_Fdat")
        self.form_Fdat.setGeometry(QRect(20, 120, 141, 31))
        self.form_Fdat.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.l_Fdat = QLabel(self.group_cData)
        self.l_Fdat.setObjectName(u"l_Fdat")
        self.l_Fdat.setGeometry(QRect(20, 90, 171, 20))
        self.l_Fdat.setFont(font8)
        self.group_prods = QGroupBox(self.p_crearF)
        self.group_prods.setObjectName(u"group_prods")
        self.group_prods.setGeometry(QRect(310, 10, 561, 161))
        self.btn_FaddP = QPushButton(self.group_prods)
        self.btn_FaddP.setObjectName(u"btn_FaddP")
        self.btn_FaddP.setGeometry(QRect(370, 90, 151, 61))
        self.btn_FaddP.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"border-color: rgb(255, 30, 30);")
        self.label_Fq = QLabel(self.group_prods)
        self.label_Fq.setObjectName(u"label_Fq")
        self.label_Fq.setGeometry(QRect(120, 110, 47, 13))
        self.label_Fprod = QLabel(self.group_prods)
        self.label_Fprod.setObjectName(u"label_Fprod")
        self.label_Fprod.setGeometry(QRect(120, 60, 47, 13))
        self.l_Fprod = QLabel(self.group_prods)
        self.l_Fprod.setObjectName(u"l_Fprod")
        self.l_Fprod.setGeometry(QRect(30, 20, 201, 31))
        self.l_Fprod.setFont(font8)
        self.form_Fprod = QLineEdit(self.group_prods)
        self.form_Fprod.setObjectName(u"form_Fprod")
        self.form_Fprod.setGeometry(QRect(120, 80, 191, 21))
        self.form_FprodQ = QLineEdit(self.group_prods)
        self.form_FprodQ.setObjectName(u"form_FprodQ")
        self.form_FprodQ.setGeometry(QRect(120, 130, 191, 21))
        self.stacked_facturas.addWidget(self.p_crearF)
        self.table_Fprods.raise_()
        self.table_Ftotal.raise_()
        self.l_Ftotal.raise_()
        self.group_cData.raise_()
        self.group_prods.raise_()
        self.p_listaF = QWidget()
        self.p_listaF.setObjectName(u"p_listaF")
        self.table_facturas = QTableWidget(self.p_listaF)
        if (self.table_facturas.columnCount() < 5):
            self.table_facturas.setColumnCount(5)
        __qtablewidgetitem15 = QTableWidgetItem()
        __qtablewidgetitem15.setFont(font7);
        self.table_facturas.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        __qtablewidgetitem16.setFont(font7);
        self.table_facturas.setHorizontalHeaderItem(1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        __qtablewidgetitem17.setFont(font7);
        self.table_facturas.setHorizontalHeaderItem(2, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        __qtablewidgetitem18.setFont(font7);
        self.table_facturas.setHorizontalHeaderItem(3, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        __qtablewidgetitem19.setFont(font7);
        self.table_facturas.setHorizontalHeaderItem(4, __qtablewidgetitem19)
        self.table_facturas.setObjectName(u"table_facturas")
        self.table_facturas.setGeometry(QRect(10, 40, 831, 311))
        sizePolicy.setHeightForWidth(self.table_facturas.sizePolicy().hasHeightForWidth())
        self.table_facturas.setSizePolicy(sizePolicy)
        self.table_facturas.setSizeIncrement(QSize(0, 0))
        self.table_facturas.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.table_facturas.setAutoFillBackground(False)
        self.table_facturas.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.table_facturas.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_facturas.setSelectionMode(QAbstractItemView.SingleSelection)
        self.table_facturas.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table_facturas.horizontalHeader().setCascadingSectionResizes(False)
        self.table_facturas.horizontalHeader().setDefaultSectionSize(161)
        self.l_todasf = QLabel(self.p_listaF)
        self.l_todasf.setObjectName(u"l_todasf")
        self.l_todasf.setGeometry(QRect(10, 10, 211, 20))
        self.l_todasf.setFont(font8)
        self.groupBox = QGroupBox(self.p_listaF)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 200, 831, 201))
        self.table_fproductos = QTableWidget(self.groupBox)
        if (self.table_fproductos.columnCount() < 3):
            self.table_fproductos.setColumnCount(3)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.table_fproductos.setHorizontalHeaderItem(0, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.table_fproductos.setHorizontalHeaderItem(1, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.table_fproductos.setHorizontalHeaderItem(2, __qtablewidgetitem22)
        self.table_fproductos.setObjectName(u"table_fproductos")
        self.table_fproductos.setGeometry(QRect(500, 30, 311, 141))
        self.table_fproductos.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_fname = QLabel(self.groupBox)
        self.label_fname.setObjectName(u"label_fname")
        self.label_fname.setGeometry(QRect(20, 20, 461, 31))
        font9 = QFont()
        font9.setPointSize(20)
        self.label_fname.setFont(font9)
        self.label_flastn = QLabel(self.groupBox)
        self.label_flastn.setObjectName(u"label_flastn")
        self.label_flastn.setGeometry(QRect(20, 60, 461, 31))
        self.label_flastn.setFont(font9)
        self.label_ftotal = QLabel(self.groupBox)
        self.label_ftotal.setObjectName(u"label_ftotal")
        self.label_ftotal.setGeometry(QRect(20, 100, 461, 31))
        self.label_ftotal.setFont(font9)
        self.label_fced = QLabel(self.groupBox)
        self.label_fced.setObjectName(u"label_fced")
        self.label_fced.setGeometry(QRect(20, 140, 461, 31))
        self.label_fced.setFont(font9)
        self.stacked_facturas.addWidget(self.p_listaF)
        self.btn_crearF = QPushButton(self.f_facturas)
        self.btn_crearF.setObjectName(u"btn_crearF")
        self.btn_crearF.setGeometry(QRect(270, 0, 121, 40))
        self.btn_crearF.setMinimumSize(QSize(0, 40))
        self.btn_crearF.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_listaF = QPushButton(self.f_facturas)
        self.btn_listaF.setObjectName(u"btn_listaF")
        self.btn_listaF.setGeometry(QRect(410, 0, 121, 40))
        self.btn_listaF.setMinimumSize(QSize(0, 40))
        self.btn_listaF.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_8.addWidget(self.f_facturas)

        self.stackedWidget.addWidget(self.page_3)

        self.verticalLayout_5.addWidget(self.stackedWidget)


        self.horizontalLayout_2.addWidget(self.frame_pages)


        self.verticalLayout.addWidget(self.Content)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_clientes.setText(QCoreApplication.translate("MainWindow", u"Clientes", None))
        self.btn_productos.setText(QCoreApplication.translate("MainWindow", u"Productos", None))
        self.btn_facturas.setText(QCoreApplication.translate("MainWindow", u"Facturas", None))
        ___qtablewidgetitem = self.table_clientes.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Cedula", None));
        ___qtablewidgetitem1 = self.table_clientes.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Nombre", None));
        ___qtablewidgetitem2 = self.table_clientes.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Apellido", None));
        self.gb_aClientes.setTitle(QCoreApplication.translate("MainWindow", u"Agregar / Actualizar Cliente", None))
        self.l_ced.setText(QCoreApplication.translate("MainWindow", u"C\u00e9dula (*)", None))
        self.l_nom.setText(QCoreApplication.translate("MainWindow", u"Nombre (*)", None))
        self.l_prod.setText(QCoreApplication.translate("MainWindow", u"Apellido (*)", None))
        self.btn_actualizar.setText(QCoreApplication.translate("MainWindow", u"Actualizar", None))
        self.btn_agregar.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.gb_eClientes.setTitle(QCoreApplication.translate("MainWindow", u"Eliminar Cliente", None))
        self.btn_eliminar.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.l_bCedula.setText(QCoreApplication.translate("MainWindow", u"C\u00e9dula (*)", None))
        self.group_addP.setTitle(QCoreApplication.translate("MainWindow", u"Agregar Producto", None))
        self.btn_antibiotico.setText(QCoreApplication.translate("MainWindow", u"Antibiotico", None))
        self.btn_productoControl.setText(QCoreApplication.translate("MainWindow", u"Control", None))
        self.label_antNom.setText(QCoreApplication.translate("MainWindow", u"Nombre Antibiotico (*)", None))
        self.label_dosis.setText(QCoreApplication.translate("MainWindow", u"Dosis (*)", None))
        self.label_animal.setText(QCoreApplication.translate("MainWindow", u"Tipo de Animal (*)", None))
        self.form_animal.setItemText(0, QCoreApplication.translate("MainWindow", u"Escoge una opci\u00f3n...", None))
        self.form_animal.setItemText(1, QCoreApplication.translate("MainWindow", u"Bovino", None))
        self.form_animal.setItemText(2, QCoreApplication.translate("MainWindow", u"Caprino", None))
        self.form_animal.setItemText(3, QCoreApplication.translate("MainWindow", u"Porcino", None))

        self.label_precio.setText(QCoreApplication.translate("MainWindow", u"Precio (*)", None))
        self.btn_agregarAnt.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.form_ICA.setText("")
        self.label_ICA.setText(QCoreApplication.translate("MainWindow", u"ICA (*)", None))
        self.label_nombrePro.setText(QCoreApplication.translate("MainWindow", u"Nombre Producto (*)", None))
        self.form_nombrePro.setText("")
        self.label_frec.setText(QCoreApplication.translate("MainWindow", u"Frecuencia Aplicaci\u00f3n (*)", None))
        self.form_frec.setText("")
        self.label_precioP.setText(QCoreApplication.translate("MainWindow", u"Precio (*)", None))
        self.form_precioP.setText("")
        self.btn_agregarP.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.form_nombrePro_2.setText("")
        self.label_frec_2.setText(QCoreApplication.translate("MainWindow", u"Frecuencia Aplicaci\u00f3n (*)", None))
        self.form_frec_2.setText("")
        self.form_precioP_2.setText("")
        self.form_ICA_2.setText("")
        self.label_ICA_2.setText(QCoreApplication.translate("MainWindow", u"ICA (*)", None))
        self.label_precioP_2.setText(QCoreApplication.translate("MainWindow", u"Precio (*)", None))
        self.btn_agregarP_2.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.label_nombrePro_2.setText(QCoreApplication.translate("MainWindow", u"Nombre Producto (*)", None))
        self.form_carencia.setText("")
        self.label_carencia.setText(QCoreApplication.translate("MainWindow", u"Carencia (*)", None))
        self.form_precioP_3.setText("")
        self.label_frec_3.setText(QCoreApplication.translate("MainWindow", u"Frecuencia Aplicaci\u00f3n (*)", None))
        self.btn_agregarP_3.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.label_precioP_3.setText(QCoreApplication.translate("MainWindow", u"Precio (*)", None))
        self.label_carencia_2.setText(QCoreApplication.translate("MainWindow", u"Ultima Fecha Aplicaci\u00f3n (*)", None))
        self.label_nombrePro_3.setText(QCoreApplication.translate("MainWindow", u"Nombre Producto (*)", None))
        self.label_ICA_3.setText(QCoreApplication.translate("MainWindow", u"ICA (*)", None))
        self.form_nombrePro_3.setText("")
        self.form_ICA_3.setText("")
        self.form_ultimaFechaAp.setText("")
        self.form_frec_3.setText("")
        self.btn_productoControl_2.setText(QCoreApplication.translate("MainWindow", u"Fertilizante", None))
        self.btn_productoControl_3.setText(QCoreApplication.translate("MainWindow", u"Plaga", None))
        self.group_delP.setTitle(QCoreApplication.translate("MainWindow", u"Eliminar Producto", None))
        self.label_eProd.setText(QCoreApplication.translate("MainWindow", u"Nombre Producto (*)", None))
        self.form_eProd.setText("")
        self.btn_eProd.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        ___qtablewidgetitem3 = self.table_ProductosC.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"ICA", None));
        ___qtablewidgetitem4 = self.table_ProductosC.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Nombre", None));
        ___qtablewidgetitem5 = self.table_ProductosC.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Frecuencia Ap.", None));
        ___qtablewidgetitem6 = self.table_ProductosC.horizontalHeaderItem(3)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Precio", None));
        ___qtablewidgetitem7 = self.table_Antibioticos.horizontalHeaderItem(0)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Nombre", None));
        ___qtablewidgetitem8 = self.table_Antibioticos.horizontalHeaderItem(1)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Dosis", None));
        ___qtablewidgetitem9 = self.table_Antibioticos.horizontalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Tipo Animal", None));
        ___qtablewidgetitem10 = self.table_Antibioticos.horizontalHeaderItem(3)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Precio", None));
        self.l_Ftotal.setText(QCoreApplication.translate("MainWindow", u"0", None))
        ___qtablewidgetitem11 = self.table_Fprods.horizontalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Nombre del Producto", None));
        ___qtablewidgetitem12 = self.table_Fprods.horizontalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Cantidad", None));
        ___qtablewidgetitem13 = self.table_Fprods.horizontalHeaderItem(2)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Precio", None));
        ___qtablewidgetitem14 = self.table_Ftotal.verticalHeaderItem(0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"TOTAL", None));
        self.group_cData.setTitle(QCoreApplication.translate("MainWindow", u"Creaci\u00f3n de Factura", None))
        self.l_Fced.setText(QCoreApplication.translate("MainWindow", u"Cedula (*)", None))
        self.btn_Fcreate.setText(QCoreApplication.translate("MainWindow", u"CREAR FACTURA", None))
        self.l_Fdat.setText(QCoreApplication.translate("MainWindow", u"Fecha Factura (*)", None))
        self.group_prods.setTitle(QCoreApplication.translate("MainWindow", u"Productos de la Factura", None))
        self.btn_FaddP.setText(QCoreApplication.translate("MainWindow", u"AGREGAR", None))
        self.label_Fq.setText(QCoreApplication.translate("MainWindow", u"Cantidad", None))
        self.label_Fprod.setText(QCoreApplication.translate("MainWindow", u"Nombre", None))
        self.l_Fprod.setText(QCoreApplication.translate("MainWindow", u"Agregar Producto (*)", None))
        ___qtablewidgetitem15 = self.table_facturas.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Cedula", None));
        ___qtablewidgetitem16 = self.table_facturas.horizontalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Nombre", None));
        ___qtablewidgetitem17 = self.table_facturas.horizontalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Apellido", None));
        ___qtablewidgetitem18 = self.table_facturas.horizontalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"Fecha", None));
        ___qtablewidgetitem19 = self.table_facturas.horizontalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Total", None));
        self.l_todasf.setText(QCoreApplication.translate("MainWindow", u"Todas las Facturas (*)", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Factura  ", None))
        ___qtablewidgetitem20 = self.table_fproductos.horizontalHeaderItem(0)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"Producto", None));
        ___qtablewidgetitem21 = self.table_fproductos.horizontalHeaderItem(1)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"Tipo", None));
        ___qtablewidgetitem22 = self.table_fproductos.horizontalHeaderItem(2)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"Precio x U", None));
        self.label_fname.setText(QCoreApplication.translate("MainWindow", u"Nombre:", None))
        self.label_flastn.setText(QCoreApplication.translate("MainWindow", u"Apellido:", None))
        self.label_ftotal.setText(QCoreApplication.translate("MainWindow", u"Total de la factura:", None))
        self.label_fced.setText(QCoreApplication.translate("MainWindow", u"Cedula:", None))
        self.btn_crearF.setText(QCoreApplication.translate("MainWindow", u"Crear Factura", None))
        self.btn_listaF.setText(QCoreApplication.translate("MainWindow", u"Todas las Facturas", None))
    # retranslateUi

